# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

resources:
- repo: self
  fetchDepth: 15

#trigger:
#- master

#pool:
#  name: DCT
#  demands:
#  - IsBuildServer
#  - msbuild
pool:
  vmImage: 'windows-latest'  

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs: 
    vstsFeed: '1d5deb2d-cf8b-4bb1-b147-d13bc246e3f4'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory)'


- task: MSBuild@1
  enabled: false
  inputs:
    solution: '**/*.sln'
    platform: '$(buildPlatform)'
    msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'


- task: VSTest@2
  enabled: false
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

