CREATE TABLE [Verification].[Earnings]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	LearnerUln bigint NOT NULL,
	LearnerReferenceNumber NVARCHAR(50) NOT NULL,
	Ukprn bigint NOT NULL,
	PriceEpisodeIdentifier NVARCHAR(50) NOT NULL,
	EpisodeStartDate DATETIME2 NOT NULL,
	EpisodeEffectiveTnpStartDate DATETIME2 NOT NULL,
	DeliveryPeriod int NOT NULL,
	LearningAimProgrammeType int,
	LearningAimFrameworkCode int, 
	LearningAimPathwayCode int,
	LearningAimStandardCode int, 
    [SfaContributionPercentage] DECIMAL(18, 5) NOT NULL, 
    [LearningAimFundingLineType] NVARCHAR(150) NOT NULL, 
    [LearningAimReference] NVARCHAR(50) NOT NULL, 
    [LearningStartDate] DATETIME2 NOT NULL, 
    [TransactionType01] MONEY NOT NULL, 
    [TransactionType02] MONEY NOT NULL, 
    [TransactionType03] MONEY NOT NULL, 
    [TransactionType04] MONEY NOT NULL, 
    [TransactionType05] MONEY NOT NULL, 
    [TransactionType06] MONEY NOT NULL, 
    [TransactionType07] MONEY NOT NULL, 
    [TransactionType08] MONEY NOT NULL, 
    [TransactionType09] MONEY NOT NULL, 
    [TransactionType10] MONEY NOT NULL, 
    [TransactionType11] MONEY NOT NULL, 
    [TransactionType12] MONEY NOT NULL, 
    [TransactionType13] MONEY NOT NULL, 
    [TransactionType14] MONEY NOT NULL, 
    [TransactionType15] MONEY NOT NULL, 
    [TransactionType16] MONEY NOT NULL, 
    [ContractType] INT NOT NULL, 
    [FirstIncentiveCensusDate] DATETIME NULL, 
    [SecondIncentiveCensusDate] DATETIME NULL, 
    [LearnerAdditionalPaymentsDate] DATETIME NULL, 
    [AgreedPrice] DECIMAL(18, 5) NOT NULL, 
    [EndDate] DATETIME NULL, 
    [CumulativePmrs] INT NOT NULL, 
    [ExemptionCodeForCompletionHoldback] INT NOT NULL, 
    [VerificationResult] INT NOT NULL
	

)
